# Generated by Django 4.2.17 on 2024-12-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='bigcategory',
            new_name='big_category',
        ),
    ]
