# Generated by Django 4.2.17 on 2024-12-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0002_rename_bigcategory_category_big_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='big_category',
            new_name='bigcategory',
        ),
    ]
